sonar.sources=app

# Esclusioni dall'analisi del codice generale
sonar.exclusions=public/**, prisma/migrations/**, node_modules/**, build/**, .cache/**

# Esclusioni dalla Test Coverage (solo test delle logiche)
sonar.coverage.exclusions=app/components/**, app/routes/**, app/root.tsx, app/db.server.ts